apiVersion: v1
kind: PersistentVolume
metadata:
  name: userdb-v
  labels:
    app: userdb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: "/tmp/userdb-data"
  persistentVolumeReclaimPolicy: Delete

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: userdb-v-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
