apiVersion: v1
kind: PersistentVolume
metadata:
  name: userdb-v
  labels:
    app: userdb
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
