// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"database/sql"
	"github.com/google/wire"
	"log/slog"
	"user_service/internal/application/use_cases/user"
	"user_service/internal/application/use_cases/user_profile"
	"user_service/internal/domain/repositories"
	"user_service/internal/domain/services"
	"user_service/internal/infrastructure"
	"user_service/internal/presentations/user_controller"
	userprofile2 "user_service/internal/presentations/user_profile"
)

// Injectors from wire.go:

func Initialize(logger *slog.Logger, db *sql.DB) *ControllerSet {
	userRepositoryImpl := ProviderUserRepository(logger, db)
	emailDuplicateChecker := services.NewEmailDuplicateService(userRepositoryImpl)
	userRegisterAdminUser := user.NewRegisterAdminUser(logger, emailDuplicateChecker, userRepositoryImpl)
	getUserById := user.NewGetUserById(logger, userRepositoryImpl)
	userController := usercontroller.NewUserController(logger, userRegisterAdminUser, getUserById)
	editProfile := userprofile.NewEditProfile(logger, userRepositoryImpl)
	userProfileController := userprofile2.NewUserProfileController(logger, editProfile)
	controllerSet := &ControllerSet{
		UserController:            userController,
		EditUserProfileController: userProfileController,
	}
	return controllerSet
}

// wire.go:

func ProviderUserRepository(logger *slog.Logger, db *sql.DB) *infrastructure.UserRepositoryImpl {
	repository := infrastructure.NewUserRepositoryImpl(logger, db)
	return repository
}

var userRepositorySet = wire.NewSet(
	ProviderUserRepository, wire.Bind(new(repositories.UserRepository), new(*infrastructure.UserRepositoryImpl)),
)

var emailDuplicateCheckerSet = wire.NewSet(services.NewEmailDuplicateService)

var registerAdminUser = wire.NewSet(user.NewRegisterAdminUser)

var getByUserId = wire.NewSet(user.NewGetUserById)

var editUserProfile = wire.NewSet(userprofile.NewEditProfile)

var userControllerSet = wire.NewSet(usercontroller.NewUserController)

var userProfileControllerSet = wire.NewSet(userprofile2.NewUserProfileController)

type ControllerSet struct {
	UserController            *usercontroller.UserController
	EditUserProfileController *userprofile2.UserProfileController
}
